"use client";
import { useEffect, useState } from "react";
type Item = { id: string; name: string; description?: string | null };
export default function OrganizationPage() {
  const [type, setType] = useState("groups"); const [name, setName] = useState(""); const [items, setItems] = useState<Item[]>([]); const [message, setMessage] = useState("");
  async function load() { const response = await fetch(`/api/v1/places?type=${type}`); const body = await response.json(); setItems(body.data || []); }
  useEffect(() => { void load(); }, [type]);
  async function save(event: React.FormEvent) { event.preventDefault(); const response = await fetch("/api/v1/places", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type, name }) }); const body = await response.json(); setMessage(response.ok ? "Guardado correctamente." : body.error?.message || "No se pudo guardar."); if (response.ok) { setName(""); void load(); } }
  return <main className="shell"><aside className="sidebar"><a className="brand" href="/">PROCREARE</a><div className="farm">Finca principal<span>Organización</span></div><nav><a href="/">Inicio</a><a href="/animales">Animales</a><a href="/stock">Stock</a><a className="active" href="/organizacion">Organización</a><a href="/reportes">Reportes</a></nav></aside><section className="content"><header><div><div className="eyebrow">ESTRUCTURA DE LA FINCA</div><h1>Organización</h1><p className="lead">Define grupos, lotes y ubicaciones para cada animal.</p></div></header><div className="empty-actions">{[["groups","Grupos"],["lots","Lotes"],["locations","Ubicaciones"]].map(([value, label]) => <button key={value} className={type === value ? "button" : "secondary"} onClick={() => setType(value)}>{label}</button>)}</div><article className="surface"><form className="form-grid" onSubmit={save}><label className="full-width">Nombre<input required value={name} onChange={event => setName(event.target.value)} placeholder="Ej.: Rodeo norte" /></label><div className="sheet-actions full-width"><button className="button">Agregar</button></div></form>{message && <p className="notice">{message}</p>}</article><article className="surface table-surface"><h2>{type === "groups" ? "Grupos" : type === "lots" ? "Lotes" : "Ubicaciones"}</h2><div className="table-wrap"><table><thead><tr><th>Nombre</th><th>Descripción</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.name}</td><td>{item.description || "—"}</td></tr>)}</tbody></table></div></article></section></main>;
}
