"use client";
import { FormEvent, useEffect, useState } from "react";
type Animal = { id: string; internalId: string; breed: string };
export default function SalesPage() {
  const [animals, setAnimals] = useState<Animal[]>([]); const [animalId, setAnimalId] = useState(""); const [buyerName, setBuyerName] = useState(""); const [totalAmount, setTotalAmount] = useState(""); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/v1/animals").then((r) => r.json()).then((p) => setAnimals(p.data ?? [])).catch(() => setMessage("No se pudieron cargar los animales.")); }, []);
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); try { const response = await fetch("/api/v1/sales", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ date, buyerName, priceMode: "PER_HEAD", totalAmount: Number(totalAmount), items: [{ animalId, unitPrice: Number(totalAmount), lineTotal: Number(totalAmount) }] }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? "No se pudo registrar la venta."); setMessage("Venta registrada correctamente."); setBuyerName(""); setTotalAmount(""); setAnimalId(""); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo registrar la venta."); } finally { setSaving(false); } }
  return <main className="shell"><aside className="sidebar"><a className="brand" href="/">PROCREARE</a><div className="farm">Finca principal<span>Ventas</span></div><nav><a href="/">Inicio</a><a href="/animales">Animales</a><a href="/pesajes/lote">Pesajes</a><a className="active" href="/ventas">Ventas</a><a href="/importar">Importar</a></nav></aside><section className="content"><header><div><div className="eyebrow">SALIDAS DE LA FINCA</div><h1>Ventas</h1><p className="lead">Registra la salida de un animal activo.</p></div></header><form className="surface form-grid" onSubmit={save}><label>Animal<select value={animalId} onChange={(e) => setAnimalId(e.target.value)} required><option value="">Seleccionar animal</option>{animals.map((animal) => <option key={animal.id} value={animal.id}>{animal.internalId} · {animal.breed}</option>)}</select></label><label>Fecha<input type="date" value={date} onChange={(e) => setDate(e.target.value)} required /></label><label>Comprador<input value={buyerName} onChange={(e) => setBuyerName(e.target.value)} minLength={2} required /></label><label>Importe total<input type="number" min="0" step="1" value={totalAmount} onChange={(e) => setTotalAmount(e.target.value)} required /></label><div className="full-width sheet-actions"><button className="button" disabled={saving}>{saving ? "Guardando…" : "Registrar venta"}</button></div>{message && <p className="form-error full-width" role="status">{message}</p>}</form></section></main>;
}
