import { NextResponse } from "next/server";
import { z } from "zod";
import { requireSession } from "../../../../src/server/auth/session";
import { createAnimal, deleteAnimal, listAnimals, updateAnimal } from "../../../../src/server/services/animals";
export const runtime = "nodejs";
export async function GET(request: Request) { try { const ctx=await requireSession(); const search=new URL(request.url).searchParams.get("search")||undefined; return NextResponse.json({data:await listAnimals(ctx,search)}); } catch(error) { const code=error instanceof Error?error.message:"INTERNAL"; return NextResponse.json({error:{code,message:code==="UNAUTHENTICATED"?"Debe ingresar para continuar.":"No tiene permiso para ver estos datos."}},{status:code==="UNAUTHENTICATED"?401:403}); } }
export async function POST(request: Request) { try { const ctx=await requireSession(); const result=await createAnimal(ctx, z.any().parse(await request.json())); return NextResponse.json({data:result},{status:201}); } catch(error) { const code=error instanceof Error?error.message:"INTERNAL"; return NextResponse.json({error:{code,message:code==="FORBIDDEN"?"Su rol no permite crear animales.":"No se pudo guardar el animal."}},{status:code==="FORBIDDEN"?403:400}); } }
export async function PATCH(request: Request) { try { const ctx=await requireSession(); const body=await request.json(); const id=z.string().uuid().parse(body.id); const result=await updateAnimal(ctx,id,body); return NextResponse.json({data:result}); } catch(error) { const code=error instanceof Error?error.message:"INTERNAL"; return NextResponse.json({error:{code,message:code==="FORBIDDEN"?"Su rol no permite editar animales.":code==="NOT_FOUND"?"No se encontró el animal.":"No se pudo actualizar el animal."}},{status:code==="FORBIDDEN"?403:400}); } }
export async function DELETE(request: Request) { try { const ctx=await requireSession(); const id=z.string().uuid().parse(new URL(request.url).searchParams.get("id")); await deleteAnimal(ctx,id); return NextResponse.json({data:{ok:true}}); } catch(error) { const code=error instanceof Error?error.message:"INTERNAL"; return NextResponse.json({error:{code,message:code==="FORBIDDEN"?"Su rol no permite eliminar animales.":code==="NOT_FOUND"?"No se encontró el animal.":"No se pudo eliminar el animal."}},{status:code==="FORBIDDEN"?403:400}); } }
