"use client";
import { useEffect, useState } from "react";
type Animal = { id: string; internalId: string; name?: string | null; eid?: string | null; breed: string; sex: string; category: string; status: string };
export default function AnimalsPage() {
  const [animals, setAnimals] = useState<Animal[]>([]); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); try { const r = await fetch(`/api/v1/animals${search ? `?search=${encodeURIComponent(search)}` : ""}`); const b = await r.json(); if (!r.ok) throw Error(b.error?.message || "No se pudieron cargar los animales."); setAnimals(b.data || []); } catch (e) { setError(e instanceof Error ? e.message : "No se pudieron cargar los animales."); } finally { setLoading(false); } }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 200); return () => window.clearTimeout(timer); }, [search]);
  return <main className="shell"><aside className="sidebar"><a className="brand" href="/">PROCREARE</a><div className="farm">Finca principal<span>Gestión ganadera</span></div><nav><a href="/">Inicio</a><a className="active" href="/animales">Animales</a><a href="/stock">Stock</a><a href="/laboratorio">Laboratorio</a><a href="/reportes">Reportes</a></nav></aside><section className="content"><header><div><div className="eyebrow">GESTIÓN DE LA FINCA</div><h1>Animales</h1><p className="lead">Selecciona un animal para abrir su ficha completa, editarlo y consultar toda su historia.</p></div><a className="button" href="/animales-masivo">Importar animales</a></header><section className="toolbar surface"><label className="search-field"><span aria-hidden="true">⌕</span><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar por caravana, EID o raza" aria-label="Buscar animales" /></label><span className="toolbar-meta">{loading ? "Cargando…" : `${animals.length} animales`}</span></section>{error && <div className="alert" role="alert">{error}</div>}<section className="surface table-surface"><div className="section-heading"><div><h2>Rodeo activo</h2><p className="muted">Abre la ficha con “Ver ficha” o haciendo clic en la caravana.</p></div></div>{loading ? <div className="loading-state"><span className="spinner" /> Cargando animales…</div> : animals.length === 0 ? <div className="empty-state"><h3>No hay animales para mostrar</h3><p className="muted">Importa una planilla o agrega animales para comenzar.</p></div> : <div className="table-wrap"><table><thead><tr><th>Caravana</th><th>Nombre</th><th>EID</th><th>Sexo</th><th>Categoría</th><th>Raza</th><th>Estado</th><th /></tr></thead><tbody>{animals.map(animal => <tr key={animal.id}><td><a className="animal-link" href={`/animales/${animal.id}`}><strong>{animal.internalId}</strong></a></td><td>{animal.name || "—"}</td><td>{animal.eid || "—"}</td><td>{animal.sex === "FEMALE" ? "Hembra" : "Macho"}</td><td><span className="badge">{animal.category}</span></td><td>{animal.breed}</td><td>{animal.status === "ACTIVE" ? "Activo" : animal.status}</td><td className="row-actions"><a className="icon-button" href={`/animales/${animal.id}`}>Ver ficha</a></td></tr>)}</tbody></table></div>}</section></section></main>;
}
