"use client";
import { useEffect, useState } from "react";

type Dashboard = { farm?: { name: string; currency: string }; activeAnimals: number; averageWeight: number | null; salesYear: number; salesCount: number };
const money = (amount: number, currency = "PYG") => new Intl.NumberFormat("es-PY", { style: "currency", currency, maximumFractionDigits: 0 }).format(amount);

export default function Home() {
  const [data, setData] = useState<Dashboard | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/v1/dashboard").then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? "No se pudo cargar el resumen."); setData(payload.data); }).catch((exception) => setError(exception instanceof Error ? exception.message : "No se pudo cargar el resumen.")); }, []);
  const stats = [["Animales activos", data ? String(data.activeAnimals) : "—", "Estado actual de la finca"], ["Peso promedio", data?.averageWeight ? `${data.averageWeight.toFixed(1)} kg` : "—", "Últimos pesajes registrados"], ["Ventas este año", data ? money(data.salesYear, data.farm?.currency) : "—", `${data?.salesCount ?? 0} operaciones`]];
  return <main className="shell"><aside className="sidebar"><a className="brand" href="/">PROCREARE</a><div className="farm">{data?.farm?.name ?? "Finca principal"}<span>{data ? "Datos conectados" : "Cargando resumen…"}</span></div><nav><a className="active" href="/">Inicio</a><a href="/animales">Animales</a><a href="/pesajes/lote">Pesajes</a><a href="/ventas">Ventas</a><a href="/importar">Importar</a><a href="/configuracion-inicial">Ajustes</a></nav></aside><section className="content"><header><div><div className="eyebrow">RESUMEN DE LA FINCA</div><h1>Inicio</h1><p className="lead">Una vista rápida del estado de tu finca.</p></div><a className="button" href="/animales">Agregar animal</a></header>{error && <div className="alert" role="alert">{error} <a href="/ingresar">Ingresar</a></div>}<div className="stats">{stats.map(([title,value,help])=><article className="stat" key={title}><span>{title}</span><strong>{value}</strong><small>{help}</small></article>)}</div><div className="grid"><article className="surface"><h2>Gestiona tu finca</h2><p className="muted">Registra animales, pesajes e importa tus planillas de Excel con datos aislados por finca.</p><div className="empty-actions"><a className="button" href="/animales">Ver animales</a><a className="secondary" href="/importar">Importar desde Excel</a></div></article><article className="surface"><h2>Acciones rápidas</h2><ol className="steps"><li><a href="/pesajes/lote">Registrar un pesaje</a></li><li><a href="/ventas">Registrar una venta</a></li><li><a href="/configuracion-inicial">Revisar configuración</a></li></ol></article></div></section></main>;
}
