import { spawnSync } from "node:child_process";
const pooled = process.env.DATABASE_URL || process.env.POSTGRES_PRISMA_URL || process.env.POSTGRES_URL;
const direct = process.env.DATABASE_URL_UNPOOLED || process.env.POSTGRES_URL_NON_POOLING || pooled;
if (pooled) process.env.DATABASE_URL = pooled;
if (direct) process.env.DATABASE_URL_UNPOOLED = direct;
const args = process.argv.slice(2);
if (args[0] === "--") args.shift();
if (!args.length) throw new Error("Usage: resolve-db-env.mjs -- <command> [args]");
const result = spawnSync(args[0], args.slice(1), { stdio: "inherit", env: process.env });
if (result.error) throw result.error;
process.exit(result.status ?? 1);
