"use client";
import { FormEvent, useEffect, useState } from "react";
type Animal = { id: string; internalId: string; breed: string };
export default function BatchWeighingPage() {
  const [animals, setAnimals] = useState<Animal[]>([]); const [animalId, setAnimalId] = useState(""); const [weightKg, setWeightKg] = useState(""); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [type, setType] = useState("ROUTINE"); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/v1/animals").then((r) => r.json()).then((p) => setAnimals(p.data ?? [])).catch(() => setMessage("No se pudieron cargar los animales.")); }, []);
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); try { const response = await fetch("/api/v1/weighings", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ animalId, date, weightKg: Number(weightKg), type }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? "No se pudo guardar el pesaje."); setMessage("Pesaje guardado correctamente."); setWeightKg(""); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo guardar el pesaje."); } finally { setSaving(false); } }
  return <main className="shell"><aside className="sidebar"><a className="brand" href="/">PROCREARE</a><div className="farm">Finca principal<span>Pesaje por lote</span></div><nav><a href="/">Inicio</a><a href="/animales">Animales</a><a className="active" href="/pesajes/lote">Pesajes</a><a href="/ventas">Ventas</a><a href="/importar">Importar</a></nav></aside><section className="content"><header><div><div className="eyebrow">REGISTRO RÁPIDO</div><h1>Pesaje por lote</h1><p className="lead">Registra un pesaje y continúa con el siguiente animal.</p></div></header><form className="surface form-grid" onSubmit={save}><label>Animal<select value={animalId} onChange={(e) => setAnimalId(e.target.value)} required><option value="">Seleccionar animal</option>{animals.map((animal) => <option key={animal.id} value={animal.id}>{animal.internalId} · {animal.breed}</option>)}</select></label><label>Fecha<input type="date" value={date} onChange={(e) => setDate(e.target.value)} required /></label><label>Peso en kg<input type="number" min="0.1" max="1500" step="0.1" value={weightKg} onChange={(e) => setWeightKg(e.target.value)} required /></label><label>Tipo<select value={type} onChange={(e) => setType(e.target.value)}><option value="ROUTINE">Rutina</option><option value="WEANING">Destete</option><option value="INITIAL">Inicial</option><option value="SALE">Venta</option></select></label><div className="full-width sheet-actions"><button className="button" disabled={saving}>{saving ? "Guardando…" : "Guardar pesaje"}</button></div>{message && <p className="form-error full-width" role="status">{message}</p>}</form></section></main>;
}
